apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go-deployment
  labels:
    app: hello-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
        - name: hello-go
          image: ghcr.io/codequokka/hello-go:1.0.0
          ports:
            - containerPort: 8180